dist: trusty
language: cpp

addons:
  apt:
    sources:
    - sourceline: 'deb https://apt.llvm.org/trusty llvm-toolchain-trusty-5.0 main'
      key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
    - python3-pip
    - python-virtualenv
    - git
    - clang-5.0
    - make

before_install:
  - export CC=clang-5.0
  - export CXX=clang++-5.0

before_script:
  - make --version
  - $CXX --version

script:
  - make test
