#!/usr/bin/python3

import os
import sys

sys.path.insert(0, '../../drake/src')

import drake
import drake.cxx

cfg = drake.cxx.Config()
cfg.enable_debug_symbols()
cfg.enable_optimization()

with drake.Drake('../..') as d:
  d.run(
    cxx_config = cfg,
  )
